services:
  ollama:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 4G  # Increase memory limit to 4GB
        reservations:
          memory: 2G  # Reserve at least 2GB
    restart: unless-stopped

volumes:
  ollama_data: