services:
  ollama:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G  # Memory limit for llama2
        reservations:
          memory: 4G  # Reserve at least 4GB
    restart: unless-stopped

volumes:
  ollama_data: